env                  = "dev"
region               = "us-east-1"
vpc_cidr             = "10.0.0.0/16"
instance_size        = "t2.micro"
db_user              = "postgres"
db_password          = "postgres_password"
app_ami_id           = "ami-002192a70217ac181" # find valid
app_instance_type    = "t2.micro"
db_port              = 5432
app_desired_capacity = 2
app_max_size         = 4
app_min_size         = 2
db_size              = "db.t3.micro"
cidr_block           = "0.0.0.0/0"
create_nat_gateway   = true
locust_allowed_cidr  = "194.44.131.113/32"